###
GET http://localhost:8080/1 HTTP/1.1
Host: localhost:8080
User-Agent: curl/8.6.0
Accept: */*
###
HTTP/1.1 201 Created
Content-Type: application/json
Location: http://localhost:8080/1

{
  "message": "New user created 1",
  "user": {
    "id": 123,
    "firstName": "Example 1",
    "lastName": "Person 1",
    "email": "bsmth@localhost:8080 1"
  }
}
###
GET http://example.com HTTP/1.1
User-Agent: curl/8.6.0
Accept: */*
###
GET http://localhost:8080/3 HTTP/1.1
Host: localhost:8080
User-Agent: curl/8.6.0
Accept: */*
###
HTTP/1.1 201 Created
Content-Type: application/json
Location: http://localhost:8080/users/3

{
  "message": "New user created 2",
  "user": {
    "id": 123,
    "firstName": "Example 2",
    "lastName": "Person 2",
    "email": "bsmth@example.com 2"
  }
}
###